modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20End%20Portal%20Recipe"
logoFile="icon.png"

[[mods]]
modId="endportalrecipe"
version="5.0"
displayName="End Portal Recipe"
displayURL="https://curseforge.com/minecraft/mc-mods/end-portal-recipe"
authors="Rick South"
description='''Makes the end portal craftable and available in survival via a recipe and adds an extra dragon egg drop to create it. The portal can be picked up via silk touch.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.endportalrecipe]]
    modId="collective"
    mandatory=true
    versionRange="[6.20,)"
    ordering="NONE"
    side="BOTH"